name: Build Chrome Extension

on:
  # Run on pushes to the main branch
  push:
    branches: [ "main" ]
  
  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Read the version from manifest.json
      - name: Read extension version
        id: manifest
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
        
      # Step 3: Create a build directory and copy files
      - name: Create build directory and copy files
        run: |
          mkdir build
          cp manifest.json build/
          cp content.js build/
          cp styles.css build/
          cp lightweight-charts.standalone.production.js build/
          cp icon.png build/

      # === Step 4: Build ZIP file (for Chrome Web Store) ===
      - name: Create ZIP file
        run: |
          cd build
          zip -r ../cs2-trade-extention-v${{ steps.manifest.outputs.version }}.zip .
          cd ..

      # === Step 5: Build CRX file (for testing/manual distribution) ===
      # Using a new, active action
      - name: Build CRX file
        uses: its-rn/action-pack-chrome-extension@v1
        with:
          # This tells the action where your extension files are
          src_dir: 'build'
          
          # This tells the action to name the output file
          crx_name: 'cs2-trade-extention-v${{ steps.manifest.outputs.version }}'
          
          # This uses the private key you stored in GitHub Secrets
          pem_key: ${{ secrets.CRX_PRIVATE_KEY }}
          
          # Required filename for the private key on the runner
          pem_name: 'key.pem'

      # === Step 6: Upload BOTH files as artifacts ===
      - name: Upload ZIP artifact (for Web Store)
        uses: actions/upload-artifact@v4
        with:
          name: cs2-trade-extention-ZIP
          path: cs2-trade-extention-v${{ steps.manifest.outputs.version }}.zip

      - name: Upload CRX artifact (for Testing)
        uses: actions/upload-artifact@v4
        with:
          name: cs2-trade-extention-CRX
          path: cs2-trade-extention-v${{ steps.manifest.outputs.version }}.crx

