name: Build Chrome Extension

on:
  # Run on pushes to the main branch
  push:
    branches: [ "main" ]
  
  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Read the version from manifest.json
      - name: Read extension version
        id: manifest
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
        
      # Step 3: Create a build directory and copy files
      - name: Create build directory and copy files
        run: |
          mkdir build
          cp manifest.json build/
          cp content.js build/
          cp styles.css build/
          cp lightweight-charts.standalone.production.js build/
          cp icon.png build/

      # === Step 4: Build ZIP file (for Chrome Web Store) ===
      - name: Create ZIP file
        run: |
          cd build
          zip -r ../cs2-trade-extention-v${{ steps.manifest.outputs.version }}.zip .
          cd ..

      # === Step 5: Build CRX file (using Google Chrome directly) ===
      - name: Build CRX file
        run: |
          # 1. Save the private key from GitHub Secrets to a file
          echo "${{ secrets.CRX_PRIVATE_KEY }}" > key.pem
          
          # 2. Use Google Chrome's built-in packer
          # This command is available on ubuntu-latest runners
          google-chrome --pack-extension=./build --pack-extension-key=./key.pem
          
          # 3. Rename the output file (it's named 'build.crx' by default)
          mv build.crx cs2-trade-extention-v${{ steps.manifest.outputs.version }}.crx

      # === Step 6: Upload BOTH files as artifacts ===
      - name: Upload ZIP artifact (for Web Store)
        uses: actions/upload-artifact@v4
        with:
          name: cs2-trade-extention-ZIP
          path: cs2-trade-extention-v${{ steps.manifest.outputs.version }}.zip

      - name: Upload CRX artifact (for Testing)
        uses: actions/upload-artifact@v4
        with:
          name: cs2-trade-extention-CRX
          path: cs2-trade-extention-v${{ steps.manifest.outputs.version }}.crx

